In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('../../src')

In [2]:
from simuq.ionq_arb_2q import IonQProvider
ionq = IonQProvider(from_file="../../../ionq_API_key")

In [4]:
from simuq import QSystem, Qubit
import numpy as np
import scipy as sp
X=np.array([[0,1],[1,0]])
Y=np.array([[0,-1j],[1j,0]])
Z=np.array([[1,0],[0,-1]])


In [13]:
qs = QSystem()
q0, q1 = Qubit(qs), Qubit(qs)
h = q0.X*q1.Y+q0.X*q1.X*0.5
qs.add_evolution(h, 1)
ionq.compile(qs)
solved_unitary=ionq.prog_obj.to_matrix()
h1=np.kron(X,Y)+np.kron(X,X)*0.5
ideal_unitary=sp.linalg.expm(-1j*h1)

/home/pengyul/SimuQ/notebooks/experimental/../../src/simuq/backends/ionq_transpiler_arb_2q.py:241: ComplexWarning: Casting complex values to real discards the imaginary part
  bounds = np.array(
/home/pengyul/SimuQ/notebooks/experimental/../../src/simuq/backends/ionq_transpiler_arb_2q.py:244: ComplexWarning: Casting complex values to real discards the imaginary part
  x0 = np.random.rand(5 * i) * np.array(


success with  1  terms
[[[ 1.49534878 -0.          0.        ]
  [ 0.66874031  1.33748061  0.        ]]]
{'lang': 'json', 'name': 'test', 'target': 'qpu.aria-1', 'input': {'gateset': 'native', 'qubits': 2, 'circuit': [{'gate': 'gpi', 'target': 0, 'phase': 0.0}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819095131351], 'angle': 0.059313545260654105}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819095131351], 'angle': 0.059313545260654105}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819095131351], 'angle': 0.059313545260654105}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819095131351], 'angle': 0.059313545260654105}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819095131351], 'angle': 0.059313545260654105}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819095131351], 'angle': 0.059313545260654105}, {'gate': 'gpi', 'target': 0, 'phase': 0.0}]}, 'noise': {'model': 'aria-1'}}


In [16]:
qs = QSystem()
q0, q1 = Qubit(qs), Qubit(qs)
h = q0.X*q1.Y+q0.X*q1.X*0.5
qs.add_evolution(h, 1)
ionq.compile(qs)
solved_unitary=ionq.prog_obj.to_matrix()
h1=np.kron(X,Y)+np.kron(X,X)*0.5
ideal_unitary=sp.linalg.expm(-1j*h1)

success with  1  terms
[[[1.49534878 0.         0.        ]
  [0.66874031 1.3374806  0.        ]]]
{'lang': 'json', 'name': 'test', 'target': 'qpu.aria-1', 'input': {'gateset': 'native', 'qubits': 2, 'circuit': [{'gate': 'gpi', 'target': 0, 'phase': 0.0}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819061167986], 'angle': 0.05931354498976071}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819061167986], 'angle': 0.05931354498976071}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819061167986], 'angle': 0.05931354498976071}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819061167986], 'angle': 0.05931354498976071}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819061167986], 'angle': 0.05931354498976071}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.17620819061167986], 'angle': 0.05931354498976071}, {'gate': 'gpi', 'target': 0, 'phase': 0.0}]}, 'noise': {'model': 'aria-1'}}


In [17]:
tmp=solved_unitary@ideal_unitary.T.conj()
tmp/=tmp[0,0]
print(np.linalg.norm(tmp-np.eye(4)))

1.4032723085703273e-08


In [20]:
qs = QSystem()
q0, q1 = Qubit(qs), Qubit(qs)
h = q0.X*q1.X+q0.Y*q1.Y
qs.add_evolution(h, 1)
ionq.compile(qs, trotter_num=6,
        trotter_mode=1)
solved_unitary=ionq.prog_obj.to_matrix()
h1=np.kron(Y,Y)+np.kron(X,X)
ideal_unitary=sp.linalg.expm(-1j*h1)

success with  2  terms
[[[1.41421356e+00 0.00000000e+00 0.00000000e+00]
  [1.41421356e+00 0.00000000e+00 0.00000000e+00]]

 [[5.63868020e-10 1.41421356e+00 0.00000000e+00]
  [3.59014022e-09 1.41421356e+00 4.66818034e-10]]]
{'lang': 'json', 'name': 'test', 'target': 'qpu.aria-1', 'input': {'gateset': 'native', 'qubits': 2, 'circuit': [{'gate': 'gpi', 'target': 0, 'phase': 0.0}, {'gate': 'gpi', 'target': 1, 'phase': 0.0}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.0], 'angle': 0.05305164772684366}, {'gate': 'gpi', 'target': 0, 'phase': 0.0}, {'gate': 'gpi', 'target': 1, 'phase': 0.0}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.2499999999365426, 0.24999999959596728], 'angle': 0.05305164783465997}, {'gate': 'gpi', 'target': 0, 'phase': 0.0}, {'gate': 'gpi', 'target': 1, 'phase': 0.0}, {'gate': 'ms', 'targets': [0, 1], 'phases': [0.0, 0.0], 'angle': 0.05305164772684366}, {'gate': 'gpi', 'target': 0, 'phase': 0.0}, {'gate': 'gpi', 'target': 1, 'phase': 0.0}, {'gate': 'ms', 'targ

In [21]:
tmp=solved_unitary@ideal_unitary.T.conj()
tmp/=tmp[0,0]
print(np.linalg.norm(tmp-np.eye(4)))

6.9311486324817295e-09
